/**
 * Expo Config Plugin untuk mengkonfigurasi Android signing.
 * 
 * Plugin ini menambahkan signingConfigs ke build.gradle dan mengatur
 * buildTypes.release untuk menggunakan signing config tersebut.
 * 
 * Keystore dan credentials dibaca dari:
 * - android/keystore.jks (file keystore)
 * - android/keystore.properties (credentials)
 */

const { withAppBuildGradle } = require('@expo/config-plugins');

module.exports = function withSigning(config) {
  return withAppBuildGradle(config, (config) => {
    const contents = config.modResults.contents;

    // 1. Tambahkan pembacaan keystore.properties di bagian atas file
    const keystorePropertiesCode = `
// Signing config - generated by withSigning plugin
def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

`;

    // Sisipkan setelah deklarasi plugins
    if (!contents.includes('keystorePropertiesFile')) {
      config.modResults.contents = contents.replace(
        /apply plugin: "com.android.application"/,
        `apply plugin: "com.android.application"${keystorePropertiesCode}`
      );
    }

    // 2. Tambahkan signingConfigs
    const signingConfigCode = `    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }
`;

    // Sisipkan signingConfigs sebelum buildTypes
    if (!config.modResults.contents.includes('signingConfigs {')) {
      config.modResults.contents = config.modResults.contents.replace(
        /(\s+)buildTypes {/,
        `$1${signingConfigCode}$1buildTypes {`
      );
    }

    // 3. Update buildTypes.release untuk menggunakan signingConfig
    config.modResults.contents = config.modResults.contents.replace(
      /(\s+)release {([\s\S]*?)(\s+)}/,
      (match, indent, content, closingIndent) => {
        // Jika sudah ada signingConfig, jangan diubah
        if (content.includes('signingConfig')) {
          return match;
        }
        // Tambahkan signingConfig signingConfigs.release
        return `${indent}release {${content}${indent}    signingConfig signingConfigs.release\n${closingIndent}}`;
      }
    );

    return config;
  });
};
